stages:
  - test
  - build

container_test:
  stage: test
  image: golang:1.14-alpine
  variables:
    CGO_ENABLED: 0
    GO111MODULE: on
  script:
    - go test -cover ./pkg/...
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
