default:
  tags:
    - kubernetes

stages:
  - test
  - build

container_test:
  stage: test
  image: golang:1.14-alpine
  script:
    - CGO_ENABLED=0 GO111MODULE=on go test -cover ./pkg/...
  rules:
    - if: $CI_PIPELINE_SOURCE == "external_pull_request_event"

