apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqs-consumer
spec:
  selector:
    matchLabels:
      app: sqs-consumer
  template:
    metadata:
      labels:
        app: sqs-consumer
    spec:
      serviceAccountName: sqstest
      containers:
      - name: sqs-consumer
        image: ghcr.io/seancallaway/k8s-cloudwatch-adapter:sqs-consumer-sample
        imagePullPolicy: Always
        env:
          - name: QUEUE_NAME
            value: ""
          - name: AWS_REGION
            value: ""
